image: Visual Studio 2022

environment:
  matrix:
    - PYTHON: "C:\\Python39"
    - PYTHON: "C:\\Python311"

build: off

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "pip install numpy six"
  - "pip install six"
  - "pip install traits"
  - "pip install argparse"
  - "pip install subprocess32"
  - "python setup.py install"
  - "SET PYTHONPATH=C:\\projects\\soma-base\\python;%PYTHONPATH%"

test_script:
  - "python --version"
  - "python -m soma.tests.test_soma_base"

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_failure: true
    on_build_success: false
    on_build_status_changed: true
